[package]
name = "Kurs"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30", features = ["process", "poll", "signal"] }
config = "0.14"
serde = { version = "1", features = ["derive"] }
once_cell = "1.19"

